
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Assignation du matériel</h3>
            </div>
            <div class="panel-body">
                <p>
                    Ajouter, enlever du matériel personnel à qqn, c'est ici!
                </p>

                <p><a class="btn btn-success pull-right" href="material/materialpersonnel" >Matériel personnel</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Matériel par grade</h3>
            </div>
            <div class="panel-body">
                <p>
                    Quel est le matériel requis par un grade particulier ?
                </p>

                <p><a class="btn btn-success pull-right" href="material/materialforgrade" >Matériel par grade</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Matériel par incorporation</h3>
            </div>
            <div class="panel-body">
                <p>
                    Quel est le matériel requis par l'incorporation ?
                    <ul>
                        <li>Par la formation RECRUE,EFOR,SDIS</li>
                        <li>Par l'operationnel DPS, section d'intervention</li>
                    </ul>
                </p>

                <p><a class="btn btn-success pull-right" href="material/materialforincorp" >Matériel par incorporation</a></p>
            </div>
        </div>
    </div>
</div>
