<?php
$form = $this->form;
$form->prepare();
$form->get('firstname')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>''
    ]);
$form->get('lastname')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>''
    ]);
$form->get('grade')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>''
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
?>

<h1>Personnel</h1>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('firstname')); ?>
            <?= $this->formElement($form->get('firstname')); ?>
            <?= $this->formElementErrors($form->get('firstname')); ?>
        </div>
        <div class="form-group">    
            <?= $this->formLabel($form->get('lastname')); ?>
            <?= $this->formElement($form->get('lastname')); ?>
            <?= $this->formElementErrors($form->get('lastname')); ?>
        </div>    
        <div class="form-group"> 
            <?= $this->formLabel($form->get('grade')); ?>
            <?= $this->formElement($form->get('grade')); ?>
            <?= $this->formElementErrors($form->get('grade')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>