<div class="container">
    <h1>Liste du personnel</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Grade</th>
                <th>Actif</th>
                <th>Chauffeur</th>
                <th>APR</th>
                <th>Préposé</th>
                <th>CIPA</th>
                <th>CISDIS</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($this->persons as $person) {
              echo $this->partial('application/personnel/indexTableRow', 
                                    ['person'=>$person,
                                     'gradesVsId' => $this->gradesVsId]);
            }    
        ?>
        </tbody>
    </table>
    <a href=personnel/add class="btn btn-default">Ajouter</a>
</div>
<!-- Modal -->
<div class="modal fade" id="confirmDelete" role="dialog" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Effacer</h4>
      </div>
      <div class="modal-body">
          ...
      </div>
      <div class="modal-footer">
          <form method="POST" id="deleteForm" accept-charset="UTF-8" style="display:inline">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
            <button type="submit" class="btn btn-danger" id="confirm">Effacer</button>
          </form>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $('#confirmDelete').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var personnelName = button.attr('data-personnelName')
        var personnelId = button.attr('data-personnelId')

        var modal = $(this)
        modal.find('.modal-footer #deleteForm').attr('action','personnel/delete/' + personnelId)
        modal.find('.modal-body').text('Vous allez supprimer : ' + personnelName)
    })  
    $('#confirm').on('click', function(){
        $(this).data('form').submit();
    });
</script>