<div class="container">
    <h1>Liste du personnel</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Grade</th>
                <th>Actif</th>
                <th>Chauffeur</th>
                <th>APR</th>
                <th>Préposé</th>
                <th>CIPA</th>
                <th>CISDIS</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($this->persons as $person) {
              echo $this->partial('application/personnel/indexTableRow', ['person'=>$person]);
            }    
        ?>
        </tbody>
    </table>
    <a href=personnel/add class="btn btn-default">Ajouter</a>
</div>