<div class="container">
    <h1>Liste du personnel</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Matériel</th>
                <?php
                $grades = $this->personnalManager->getGrades();
                foreach ($grades as $grade) {
                    echo '<th>' . $grade->getName() . '</th>';
                }    
                ?>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <?php
            foreach ($this->materialForGrades as $materialRow) {
              echo $this->partial('application/material-for-grade/indexTableRow',
                                    ['materialRow'=>$materialRow,
                                     'grades' => $grades ]);
            }
        ?>
        </tbody>
    </table>
</div>