<tr>
  <td> <?= $this->materialRow->getMaterialName() ?> </td>
  <?php 
        foreach ($grades as $grade) {
            echo '<td>';
            if ($this->materialRow->getGrades()[$grade->getId()]) {
                echo $this->materialRow->getGrades()[$grade->getId()];
            }  
            echo '</td>';
        }
        ?>
  <td>
    <a href=materialforgrade/edit/<?= $this->materialRow->getMaterialId() ?> class="btn btn-default btn-xs">Editer</a>
  </td>
</tr>