<div class="jumbotron">
    <h1>Gestion du matériel à Belmont</h1>

</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Gestion du personnel</h3>
            </div>
            <div class="panel-body">
                <p>
                    Cette section se concentre sur le personnel. Ajout, changement
                    de grade, etc, ce trouvent ici.
                </p>

                <p><a class="btn btn-success pull-right" href="personnel" >Gestion du personnel</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Matériel</h3>
            </div>
            <div class="panel-body">
                <p>
                    Cette section s'occupe du matériel en soi. Qu'est ce qui est
                    disponnible. Quelles sont les tailles.
                </p>

                <p><a class="btn btn-success pull-right" href="materiel" >Gestion du matériel</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Help &amp; Support</h3>
            </div>
            <div class="panel-body">
                <p>
                    If you need any help or support while developing with ZF,
                    you may reach us via IRC: <a href="irc://irc.freenode.net/zftalk">#zftalk on Freenode</a>.
                    We'd love to hear any questions or feedback you may have
                    regarding this release. Alternatively, you may subscribe
                    and post questions to the <a href="http://framework.zend.com/archives/">mailing lists</a>.
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">Ping us on IRC &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
